package export

import (
	"fmt"
	"strings"
	"time"

	"github.com/vibelog/vibelog/pkg/types"
)

func SessionToMarkdown(session *types.Session, events []types.Event) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Session: %s\n\n", session.ID[:8]))
	b.WriteString(fmt.Sprintf("- **Repository:** `%s`\n", session.RepoPath))
	b.WriteString(fmt.Sprintf("- **Branch:** `%s`\n", session.Branch))
	b.WriteString(fmt.Sprintf("- **Started:** %s\n", session.StartedAt.Format(time.RFC3339)))
	if session.EndedAt != nil {
		b.WriteString(fmt.Sprintf("- **Ended:** %s\n", session.EndedAt.Format(time.RFC3339)))
	}
	b.WriteString("\n---\n\n")

	for _, e := range events {
		switch e.Type {
		case "prompt":
			b.WriteString(fmt.Sprintf("## 💬 Prompt (%s)\n\n%s\n\n", e.CreatedAt.Format("15:04"), e.Content))
		case "response":
			b.WriteString(fmt.Sprintf("## 🤖 Response (%s)\n\n```\n%s\n```\n\n", e.CreatedAt.Format("15:04"), e.Content))
		case "file_change":
			b.WriteString(fmt.Sprintf("## 📝 File Change (%s)\n\n", e.CreatedAt.Format("15:04")))
			if e.Metadata != "" {
				b.WriteString(fmt.Sprintf("**Metadata:** `%s`\n\n", e.Metadata))
			}
			b.WriteString(fmt.Sprintf("```\n%s\n```\n\n", e.Content))
		case "decision":
			b.WriteString(fmt.Sprintf("## 🎯 Decision (%s)\n\n**%s**\n\n", e.CreatedAt.Format("15:04"), e.Content))
			if e.Metadata != "" {
				b.WriteString(fmt.Sprintf("*Context: %s*\n\n", e.Metadata))
			}
		case "error":
			b.WriteString(fmt.Sprintf("## ❌ Error (%s)\n\n```\n%s\n```\n\n", e.CreatedAt.Format("15:04"), e.Content))
		}
	}

	b.WriteString("---\n\n*Generated by VibeLog*\n")
	return b.String()
}
